name: nabuk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2
  shared_preferences: ^2.1.0
  jwt_decode: ^0.3.1
  dio: ^5.5.0+1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  flutter_hooks: ^0.20.5
  get_it: ^8.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pretty_dio_logger: ^1.3.0

flutter:
  uses-material-design: true
